config/routes.rb
MohDatabase::Application.routes.draw do
  resources :reviews
  resources :bills
  resources :congress_people

  root 'congress_people#index'

  

end

app/models/bill.rb
class Bill < ActiveRecord::Base
	has_many :reviews
end

app/models/congress_person.rb
class CongressPerson < ActiveRecord::Base
	has_many :reviews


	def full_name
		"#{last_name}, #{first_name}"
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :congress_person
	belongs_to :bill
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bill }
      else
        format.html { render action: 'new' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:name)
    end
end

app/controllers/congress_people_controller.rb
class CongressPeopleController < ApplicationController
  before_action :set_congress_person, only: [:show, :edit, :update, :destroy]

  # GET /congress_people
  # GET /congress_people.json
  def index
    @congress_people = CongressPerson.all
  end

  # GET /congress_people/1
  # GET /congress_people/1.json
  def show
  end

  # GET /congress_people/new
  def new
    @congress_person = CongressPerson.new
  end

  # GET /congress_people/1/edit
  def edit
  end

  # POST /congress_people
  # POST /congress_people.json
  def create
    @congress_person = CongressPerson.new(congress_person_params)

    respond_to do |format|
      if @congress_person.save
        format.html { redirect_to @congress_person, notice: 'Congress person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @congress_person }
      else
        format.html { render action: 'new' }
        format.json { render json: @congress_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /congress_people/1
  # PATCH/PUT /congress_people/1.json
  def update
    respond_to do |format|
      if @congress_person.update(congress_person_params)
        format.html { redirect_to @congress_person, notice: 'Congress person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @congress_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /congress_people/1
  # DELETE /congress_people/1.json
  def destroy
    @congress_person.destroy
    respond_to do |format|
      format.html { redirect_to congress_people_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_congress_person
      @congress_person = CongressPerson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def congress_person_params
      params.require(:congress_person).permit(:first_name, :last_name, :house, :notes, :district_phone, :capitol_phone, :district, :party)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render action: 'show', status: :created, location: @review }
      else
        format.html { render action: 'new' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:congress_person_id, :bill_id, :rating, :reviewed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/congress_people_helper.rb
module CongressPeopleHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bills</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.name %></td>
        <td><%= link_to 'Show', bill %></td>
        <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
        <td><%= link_to 'Destroy', bill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bill.name %>
</p>

<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>

app/views/congress_people/_form.html.erb
<%= form_for(@congress_person) do |f| %>
  <% if @congress_person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@congress_person.errors.count, "error") %> prohibited this congress_person from being saved:</h2>

      <ul>
      <% @congress_person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :branch %><br>
    <%= f.text_field :branch %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :district_phone %><br>
    <%= f.text_field :district_phone %>
  </div>
  <div class="field">
    <%= f.label :capitol_phone %><br>
    <%= f.text_field :capitol_phone %>
  </div>
  <div class="field">
    <%= f.label :district %><br>
    <%= f.number_field :district %>
  </div>
  <div class="field">
    <%= f.label :party %><br>
    <%= f.text_field :party %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/congress_people/edit.html.erb
<h1>Editing Congress Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @congress_person %> |
<%= link_to 'Back', congress_people_path %>

app/views/congress_people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Congress People</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>branch</th>
      <th>Notes</th>
      <th>District phone</th>
      <th>Capitol phone</th>
      <th>District</th>
      <th>Party</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @congress_people.each do |congress_person| %>
      <tr>
        <td><%= congress_person.first_name %></td>
        <td><%= congress_person.last_name %></td>
        <td><%= congress_person.branch %></td>
        <td><%= congress_person.notes %></td>
        <td><%= congress_person.district_phone %></td>
        <td><%= congress_person.capitol_phone %></td>
        <td><%= congress_person.district %></td>
        <td><%= congress_person.party %></td>
        <td><%= link_to 'Show', congress_person %></td>
        <td><%= link_to 'Edit', edit_congress_person_path(congress_person) %></td>
        <td><%= link_to 'Destroy', congress_person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Congress person', new_congress_person_path %>

app/views/congress_people/new.html.erb
<h1>New Congress Person</h1>

<%= render 'form' %>

<%= link_to 'Back', congress_people_path %>

app/views/congress_people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @congress_person.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @congress_person.last_name %>
</p>

<p>
  <strong>branch:</strong>
  <%= @congress_person.branch %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @congress_person.notes %>
</p>

<p>
  <strong>District phone:</strong>
  <%= @congress_person.district_phone %>
</p>

<p>
  <strong>Capitol phone:</strong>
  <%= @congress_person.capitol_phone %>
</p>

<p>
  <strong>District:</strong>
  <%= @congress_person.district %>
</p>

<p>
  <strong>Party:</strong>
  <%= @congress_person.party %>
</p>

<table>
  <tr><th>Bill</th><th>Rating</th></tr>
  <% @congress_person.reviews.each do |review| %>
    <tr><td><%= review.bill.name %></td><td><%= review.rating %></td></tr>
  <% end %>


</table>

<%= link_to 'Edit', edit_congress_person_path(@congress_person) %> |
<%= link_to 'Back', congress_people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MohDatabase</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :congress_person %><br>
    <%= f.select :congress_person_id, CongressPerson.all.order(:last_name).collect{ |congress_person| [congress_person.full_name, congress_person.id] }  %>
  </div>
  <div class="field">
    <%= f.label :bill %><br>
    <%= f.select :bill_id, Bill.all.order(:name).collect {|bill| [bill.name, bill.id]} %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <p>1 is the lowest rating, 5 is the highest rating</p>
    <%= f.select :rating, [1,2,3,4,5] %>
  </div>
  <div class="field">
    <%= f.label :reviewed %><br>
    <%= f.check_box :reviewed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Congress person</th>
      <th>Bill</th>
      <th>Rating</th>
      <th>Reviewed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.congress_person.full_name %></td>
        <td><%= review.bill.name %></td>
        <td><%= review.rating %></td>
        <td><%= review.reviewed %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Congress person:</strong>
  <%= @review.congress_person.full_name %>
</p>

<p>
  <strong>Bill:</strong>
  <%= @review.bill.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Reviewed:</strong>
  <%= @review.reviewed %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>